import { Order } from "../models/Order.js";
import { Product } from "../models/Product.js";
import { User } from "../models/User.js";
import bcrypt from "bcryptjs";

const products = [
  {
    id: 1,
    name: "Auriculares Pro Noise-Cancelling",
    brand: "SoundMax",
    category: "electronics",
    price: 189.99,
    originalPrice: 249.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    rating: 4.8,
    reviews: 312,
    badge: "sale",
    description: "Auriculares inalambricos de alta fidelidad con cancelacion activa de ruido.",
    features: ["Cancelacion activa de ruido", "30h de bateria", "Carga USB-C"],
    stock: 45,
    colors: ["#1a1a2e", "#ffffff", "#6c3de0"],
  },
  {
    id: 2,
    name: "Smartwatch Ultra Series X",
    brand: "WristTech",
    category: "accessories",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    rating: 4.9,
    reviews: 528,
    badge: "hot",
    description: "Smartwatch con pantalla AMOLED y GPS integrado.",
    features: ["Pantalla AMOLED", "GPS", "Resistente al agua"],
    stock: 23,
    colors: ["#1a1a2e", "#c0c0c0", "#d4af37"],
  },
  {
    id: 3,
    name: "Zapatillas Runner Elite",
    brand: "RunPro",
    category: "sports",
    price: 129.99,
    originalPrice: 159.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    rating: 4.7,
    reviews: 876,
    badge: "sale",
    description: "Zapatillas de running con amortiguacion avanzada.",
    features: ["Suela de carbono", "Malla transpirable", "Peso 265g"],
    stock: 62,
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["#ff6b35", "#1a1a2e", "#f5f5f5"],
  },
  {
    id: 4,
    name: "Bolso de Cuero Premium",
    brand: "UrbanLux",
    category: "fashion",
    price: 219.99,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    rating: 4.6,
    reviews: 203,
    badge: "new",
    description: "Bolso de cuero genuino artesanal.",
    features: ["Cuero genuino", "Compartimento laptop", "Correa ajustable"],
    stock: 18,
    colors: ["#8B4513", "#1a1a2e", "#d4af37"],
  },
  {
    id: 5,
    name: "Camara Mirrorless 4K",
    brand: "PixelPro",
    category: "electronics",
    price: 899.99,
    originalPrice: 1099.99,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80",
    rating: 4.9,
    reviews: 147,
    badge: "sale",
    description: "Camara sin espejo de 24.2MP con video 4K.",
    features: ["Sensor APS-C", "Video 4K", "Estabilizador 5 ejes"],
    stock: 9,
    colors: ["#1a1a2e", "#f5f5f5"],
  },
  {
    id: 6,
    name: "Perfume Signature Collection",
    brand: "AromaLab",
    category: "beauty",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80",
    rating: 4.5,
    reviews: 421,
    badge: "new",
    description: "Fragancia exclusiva de larga duracion.",
    features: ["100ml", "Duracion 8-10 horas", "Caja regalo"],
    stock: 34,
  },
  {
    id: 7,
    name: "Lampara LED Ambient Smart",
    brand: "HomeGlow",
    category: "home",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    rating: 4.4,
    reviews: 189,
    badge: "sale",
    description: "Lampara inteligente con 16 millones de colores.",
    features: ["RGB", "Control por app", "Compatible con Alexa"],
    stock: 56,
    colors: ["#ffffff", "#1a1a2e"],
  },
  {
    id: 8,
    name: "Chaqueta Tecnica Outdoor",
    brand: "TrailCore",
    category: "sports",
    price: 169.99,
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80",
    rating: 4.7,
    reviews: 334,
    badge: "hot",
    description: "Chaqueta impermeable para aventuras al aire libre.",
    features: ["Membrana impermeable", "Costuras selladas", "Capucha ajustable"],
    stock: 27,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#2d5a27", "#1a1a2e", "#8B4513"],
  },
  {
    id: 9,
    name: "Tablet Pro 12.9\"",
    brand: "TechPad",
    category: "electronics",
    price: 749.99,
    originalPrice: 849.99,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    rating: 4.8,
    reviews: 267,
    badge: "sale",
    description: "Tablet profesional con pantalla de 120Hz.",
    features: ["Pantalla 12.9\"", "Chip de alto rendimiento", "Bateria 10h"],
    stock: 15,
    colors: ["#c0c0c0", "#1a1a2e"],
  },
  {
    id: 10,
    name: "Gafas de Sol Polarizadas",
    brand: "SunPeak",
    category: "accessories",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80",
    rating: 4.6,
    reviews: 412,
    badge: "new",
    description: "Gafas de sol con lentes polarizadas HD.",
    features: ["Lentes HD", "Montura de titanio", "Proteccion UV400"],
    stock: 43,
    colors: ["#d4af37", "#1a1a2e", "#8B4513"],
  },
  {
    id: 11,
    name: "Mochila Urban Explorer",
    brand: "CityNomad",
    category: "fashion",
    price: 94.99,
    originalPrice: 119.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    rating: 4.5,
    reviews: 653,
    badge: "sale",
    description: "Mochila urbana resistente al agua.",
    features: ["Compartimento laptop", "Puerto USB", "30L"],
    stock: 71,
    colors: ["#1a1a2e", "#6c3de0", "#f5f5f5"],
  },
  {
    id: 12,
    name: "Crema Hidratante Luxury",
    brand: "SkinNova",
    category: "beauty",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80",
    rating: 4.8,
    reviews: 891,
    badge: "hot",
    description: "Crema facial con acido hialuronico y vitamina C.",
    features: ["FPS 30", "Sin parabenos", "Dermatologicamente testada"],
    stock: 88,
  },
];

const users = [
  {
    id: 1,
    email: "admin@shoestore.local",
    full_name: "Admin Shoe Store",
    password: "Admin12345",
    role: "admin",
    is_active: true,
  },
  {
    id: 2,
    email: "ana@example.com",
    full_name: "Ana Ruiz",
    password: "customer123",
    role: "customer",
    is_active: true,
  },
  {
    id: 3,
    email: "carlos@example.com",
    full_name: "Carlos Perez",
    password: "customer123",
    role: "customer",
    is_active: true,
  },
  {
    id: 4,
    email: "laura@example.com",
    full_name: "Laura Gomez",
    password: "customer123",
    role: "customer",
    is_active: false,
  },
];

const orders = [
  {
    id: 1001,
    user_id: 2,
    customer_email: "ana@example.com",
    status: "pending",
    total: 379.98,
    created_at: new Date(),
    items: [
      { product_id: 1, product_name: "Auriculares Pro Noise-Cancelling", quantity: 2, unit_price: 189.99 },
    ],
  },
  {
    id: 1002,
    user_id: 3,
    customer_email: "carlos@example.com",
    status: "processing",
    total: 299.99,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
    items: [
      { product_id: 2, product_name: "Smartwatch Ultra Series X", quantity: 1, unit_price: 299.99 },
    ],
  },
  {
    id: 1003,
    user_id: 2,
    customer_email: "ana@example.com",
    status: "shipped",
    total: 129.99,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    items: [
      { product_id: 3, product_name: "Zapatillas Runner Elite", quantity: 1, unit_price: 129.99 },
    ],
  },
  {
    id: 1004,
    user_id: 4,
    customer_email: "laura@example.com",
    status: "delivered",
    total: 519.98,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    items: [
      { product_id: 4, product_name: "Bolso de Cuero Premium", quantity: 1, unit_price: 219.99 },
      { product_id: 10, product_name: "Gafas de Sol Polarizadas", quantity: 2, unit_price: 149.99 },
    ],
  },
  {
    id: 1005,
    user_id: 3,
    customer_email: "carlos@example.com",
    status: "cancelled",
    total: 89.99,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    items: [
      { product_id: 6, product_name: "Perfume Signature Collection", quantity: 1, unit_price: 89.99 },
    ],
  },
];

export async function seedDatabase() {
  const passwordSaltRounds = 12;
  const usersWithHashedPassword = await Promise.all(
    users.map(async (user) => ({
      ...user,
      password: await bcrypt.hash(user.password, passwordSaltRounds),
    }))
  );

  await Promise.all([Product.deleteMany({}), User.deleteMany({}), Order.deleteMany({})]);
  await Product.insertMany(products);
  await User.insertMany(usersWithHashedPassword);
  await Order.insertMany(orders);
}
